// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2lQ6lEjeQllULVEMisvzIGyJ9N3fvXbQ',
    appId: '1:192873911764:web:7b9f75e89c5bcd0bb3b241',
    messagingSenderId: '192873911764',
    projectId: 'sendnotification-cb5a7',
    authDomain: 'sendnotification-cb5a7.firebaseapp.com',
    storageBucket: 'sendnotification-cb5a7.appspot.com',
    measurementId: 'G-DG70K36KRC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjhjHHtWPZTGNPkohi0NcnDbVHNqn_5a0',
    appId: '1:192873911764:android:b22380ec74ed6c40b3b241',
    messagingSenderId: '192873911764',
    projectId: 'sendnotification-cb5a7',
    storageBucket: 'sendnotification-cb5a7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATvVvI5BxDqls2zjrFeiDK6d1thmGrHEg',
    appId: '1:192873911764:ios:b62a48e86cdebc4bb3b241',
    messagingSenderId: '192873911764',
    projectId: 'sendnotification-cb5a7',
    storageBucket: 'sendnotification-cb5a7.appspot.com',
    iosBundleId: 'com.example.cloneLocket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATvVvI5BxDqls2zjrFeiDK6d1thmGrHEg',
    appId: '1:192873911764:ios:5b6fbed0009bbf8cb3b241',
    messagingSenderId: '192873911764',
    projectId: 'sendnotification-cb5a7',
    storageBucket: 'sendnotification-cb5a7.appspot.com',
    iosBundleId: 'com.example.cloneLocket.RunnerTests',
  );
}
